// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzw0ZSFRFKQXns59E9AtSMcow87VHerkQ',
    appId: '1:373070812542:web:8c4ad5cd674424a5070f2f',
    messagingSenderId: '373070812542',
    projectId: 'task-5b6ff',
    authDomain: 'task-5b6ff.firebaseapp.com',
    storageBucket: 'task-5b6ff.firebasestorage.app',
    measurementId: 'G-SZJX0DGBJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIYOBM8pGT-cPGu-R0k2rEhXKlOkiWedk',
    appId: '1:373070812542:android:71064f94edcbcc27070f2f',
    messagingSenderId: '373070812542',
    projectId: 'task-5b6ff',
    storageBucket: 'task-5b6ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuV-5aRmY3MenSvxWlTlUsLaVHPR1Xw1c',
    appId: '1:373070812542:ios:8838ed50ffb32749070f2f',
    messagingSenderId: '373070812542',
    projectId: 'task-5b6ff',
    storageBucket: 'task-5b6ff.firebasestorage.app',
    iosBundleId: 'com.example.taskSchedjuler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuV-5aRmY3MenSvxWlTlUsLaVHPR1Xw1c',
    appId: '1:373070812542:ios:8838ed50ffb32749070f2f',
    messagingSenderId: '373070812542',
    projectId: 'task-5b6ff',
    storageBucket: 'task-5b6ff.firebasestorage.app',
    iosBundleId: 'com.example.taskSchedjuler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzw0ZSFRFKQXns59E9AtSMcow87VHerkQ',
    appId: '1:373070812542:web:b9b1fef67ecd58ae070f2f',
    messagingSenderId: '373070812542',
    projectId: 'task-5b6ff',
    authDomain: 'task-5b6ff.firebaseapp.com',
    storageBucket: 'task-5b6ff.firebasestorage.app',
    measurementId: 'G-VNG0L0WP59',
  );
}
